---
output: html_document
editor_options: 
  chunk_output_type: console
---
# R Ecology

Test the technology prep (not show notes)

## Install Packages

Run the (Setup.Rmd)[Setup.Rmd] RStudio notebook once.

## Load

```{r}
library(tidyverse)
library(lubridate)
library(ratdat)
```

## Plotting

```{r}
#install.packages("ggplot2")
```

```{r}
library(ggplot2)
library(ratdat)
?complete_old
```

```{r}
# View(complete_old)
```

```{r}
str(complete_old)
```

```{r}
ggplot(data = complete_old)
```

```{r}
ggplot(data = complete_old, mapping = aes(x = weight, y = hindfoot_length))

```

```{r}
ggplot(data = complete_old, mapping = aes(x = weight, y = hindfoot_length)) +
  geom_point()
```

```{r}
myplot <- ggplot(data = complete_old, mapping = aes(x = plot_type, y = hindfoot_length)) +
  geom_jitter(aes(color = plot_type), alpha = 0.2) +
  geom_boxplot(outlier.shape = NA, fill = NA)

myplot

myplot +
  theme_bw() +
  theme(axis.title = element_text(size = 14), 
        legend.position = "none", 
        panel.grid.major.x = element_blank()) +
  labs(title = "Rodent size by plot type",
       x = "Plot type",
       y = "Hindfoot length (mm)",
       color = "Plot type") +
  facet_wrap(vars(sex), ncol = 1)

```

## Understanding Data

```{r}
class(complete_old)
head(complete_old)

# provide a summary
summary(complete_old)
```

## Working with Data

Download Data (once)
```{r}
dir.create('data/cleaned', recursive = TRUE)
download.file('https://www.michaelc-m.com/Rewrite-R-ecology-lesson/data/cleaned/surveys_complete_77_89.csv', 'data/cleaned/surveys_complete_77_89.csv')
```

Load data
```{r}
surveys <- read_csv("data/cleaned/surveys_complete_77_89.csv")
class(surveys)
select(surveys, plot_id, species_id, hindfoot_length)
```

Write Data
```{r}
write_csv(surveys, "data/cleaned/test.csv")
```

## Databases

Setup
```{r}
dir.create('data_raw', recursive = TRUE, showWarnings = FALSE)
install.packages(c("dbplyr", "RSQLite"))
library(dplyr)
library(dbplyr)
```

Download and connect to database
```{r}
download.file(url = "https://ndownloader.figshare.com/files/2292171",
              destfile = "data_raw/portal_mammals.sqlite", mode = "wb")
mammals <- DBI::dbConnect(RSQLite::SQLite(), "data_raw/portal_mammals.sqlite")
src_dbi(mammals)
```

Run Queries
```{r}
tbl(mammals, sql("SELECT year, species_id, plot_id FROM surveys"))

surveys <- tbl(mammals, "surveys")
surveys %>%
    select(year, species_id, plot_id)

head(surveys, n = 10)
```
